# Generated by Django 4.1 on 2022-08-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_publicacion_usarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='usarios',
            new_name='usuarios',
        ),
    ]
