# Generated by Django 4.1 on 2022-08-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_usarios_publicacion_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='usuarios',
        ),
    ]
